[package]
name = "day1"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day1a"

[[bin]]
name = "day1b"

[dependencies]
criterion = "0.5.1"
itertools = "0.12.0"

[[bench]]
name = "bench"
harness = false
